services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mathai-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mathai-frontend
    ports:
      - "3000:3000"   # 👈 expose 3000
    depends_on:
      - backend
    restart: unless-stopped
